apiVersion: apps/v1
kind: Deployment
metadata:
  name: dino-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dino
  template:
    metadata:
      labels:
        app: dino
    spec:
      containers:
      - name: dino
        image: dino-nginx
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dino-service
spec:
  type: NodePort
  selector:
    app: dino
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001